use_frameworks!

target 'TDOAuth_Example' do
  pod 'TDOAuth', :path => '../'

  target 'TDOAuth_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
